on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
jobs:
  Generate-ISO:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: blue-build/github-action/iso@v1
        with:
          recipe: recipes/recipe.yml
